[[redirects]]
  from = "/api/*"
  to = "https://holiday-system-api-production.up.railway.app/:splat"
  status = 200
  force = true
  headers = { Access-Control-Allow-Origin = "https://piapdai.netlify.app/", Access-Control-Allow-Credentials = "true" }

[[redirects]]
  from = "/*"                           
  to = "/index.html"
  status = 200