[[redirects]]
  from = "/api/*"                           # Todas las rutas de la API
  to = "https://holiday-system-api-production.up.railway.app"  # URL de tu backend
  status = 200
  force = true
  headers = { Access-Control-Allow-Origin = "https://piapdai.netlify.app/", Access-Control-Allow-Credentials = "true" }

[[redirects]]
  from = "/*"                               # Todas las demás rutas
  to = "/index.html"
  status = 200